version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  connect:
    image: wurstmeister/kafka
    ports:
      - "8083:8083"
    entrypoint: /opt/kafka/bin/connect-distributed.sh /opt/kafka/config/connect-distributed.properties
    volumes:
      - ./kafka-connect/connect-distributed.properties:/opt/kafka/config/connect-distributed.properties:ro
      - ./connectors:/connectors:ro
  splunk:
    image: splunk/splunk
    environment:
      SPLUNK_PASSWORD: password
      SPLUNK_START_ARGS: "--accept-license"
    ports:
      - "8000:8000"
      - "8088:8088"
    volumes:
      - ./splunk/default.yml:/tmp/defaults/default.yml:ro